version: '3'

services:

  django_app:
    build: .
    env_file:
      - .env
    volumes:
      - static:/app/static
      - media:/app/static/media
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx
    volumes:
      - static:/app/static
      - media:/app/static/media
    ports:
      -  "80:80"
    depends_on:
      - django_app


volumes:
  static:
  media: