# Generated by Django 3.2.20 on 2023-08-16 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Help_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('date_time', models.DateTimeField()),
                ('address', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('time_over', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('eCommerce', '이커머스'), ('NFT', '블록체인'), ('public_service', '공공 서비스')], max_length=20, verbose_name='category')),
                ('helper_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helper', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
